services:
  - type: background
    name: telegram-bot-csharp
    env: docker
    plan: free
    branch: main # или ваша ветка
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: TELEGRAM_TOKEN
        fromSecret: TELEGRAM_TOKEN
